[tool.black]
line-length = 100
target-version = ['py312']

[tool.isort]
profile = "black"  # Use the Black profile for import sorting
line_length = 80
multi_line_output = 3
include_trailing_comma = true
virtual_env = "venv"
src_paths = ["libs/cafex_ui/src", "libs/cafex_api/src", "libs/cafex_core/src", "libs/cafex_db/src","libs/cafex_desktop/src"]

[tool.docformatter]
recursive = true
wrap-summaries = 100
wrap-descriptions = 100
pre-summary-newline = true
close-quotes-on-newline = true

[tool.pylint]
max-line-length = 120
disable = [
    "C0103", # (invalid-name)
    "C0114", # (missing-module-docstring)
    "C0115", # (missing-class-docstring)
    "C0116", # (missing-function-docstring)
    "R0903", # (too-few-public-methods)
    "R0913", # (too-many-arguments)
    "W0105", # (pointless-string-statement)
    "W0719", # (Raising too general exception)
    "R0914", # (Too many local variables)
    "W0718", # (catching too general exception)
]

[tool.coverage.paths]
source = ["src", ".tox/py*/**/site-packages"]

[tool.coverage.run]
branch = true
source = [
    "src",
]
omit = [
    "tests/*",
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == '__main__':",
]